# To get realpath command (updated coreutils package)
dist: xenial
sudo: false
addons:
  apt:
    packages:
    - wget
before_script:
  - ./testprograms/fetch-testprograms.bash

language: go
go:
# Needs strings.Builder, which didn't exist in 1.9
#  - "1.9"
  - "1.10"
  - "1.11"
  - tip
env:
  - GOOS=linux GOARCH=amd64
  - GOOS=linux GOARCH=arm
  - GOOS=linux GOARCH=mips
  - GOOS=windows GOARCH=amd64
  - GOOS=darwin GOARCH=amd64
install:
  - go get -v -t ./gobflib .
script:
  - go test -v ./gobflib
  - go test -v ./gobflib/il
  - go test -v -bench=. ./gobflib
