#!/bin/sh

INPUT="templates/body.go"
OUTPUT="il_const.go"
HEADER="// Code generated by go generate; DO NOT EDIT."

cat > $OUTPUT <<EOF
$HEADER

package gobflib

const mainfiletemplate=\`
EOF

cat $INPUT >> $OUTPUT

echo \` >> $OUTPUT
