// Code generated by "stringer -type=ILBlockType"; DO NOT EDIT.

package il

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ILList-0]
	_ = x[ILLoop-1]
	_ = x[ILDataPtrAdd-2]
	_ = x[ILDataAdd-3]
	_ = x[ILRead-4]
	_ = x[ILWrite-5]
	_ = x[ILDataAddVector-6]
}

const _ILBlockType_name = "ILListILLoopILDataPtrAddILDataAddILReadILWriteILDataAddVector"

var _ILBlockType_index = [...]uint8{0, 6, 12, 24, 33, 39, 46, 61}

func (i ILBlockType) String() string {
	if i >= ILBlockType(len(_ILBlockType_index)-1) {
		return "ILBlockType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ILBlockType_name[_ILBlockType_index[i]:_ILBlockType_index[i+1]]
}
