name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    # Explicitly define each test platform target.
    strategy:
      matrix:
        include:
        - GOOS: linux
          GOARCH: amd64
        - GOOS: linux
          GOARCH: arm
        - GOOS: linux
          GOARCH: mips
        - GOOS: windows
          GOARCH: amd64
        - GOOS: darwin
          GOARCH: amd64

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}
      run: |
        go build -v ./
        file ./gobf*

    - name: Fetch test programs
      run: ./testprograms/fetch-testprograms.bash

    - name: Test
      run: |
        go test -v ./gobflib
        go test -v ./gobflib/il
        go test -v -bench=. ./gobflib

    - name: Check that gen-vector-test.bash script succeeds.
      run: ./testprograms/gen-vector-test.bash
