#!/bin/bash

HEADER="// Code generated by gen_template_const.go; DO NOT EDIT."
PACKAGE=lang
OUTPUT=template_consts.go

exec 1>$OUTPUT
cat <<-EOF
$HEADER

package $PACKAGE
EOF

for template in templates/*.go; do
	name=$(basename $template .go)
	echo
	echo "const templateConst${name^} = \`"
	cat $template
	echo "\`"
done
