// Code generated by go generate; DO NOT EDIT.

package lang

const templateConstMain = `
{{ define "read" }}
readb()
{{ end }}
{{ define "write" }}
writeb( {{- . -}} )
{{ end }}
{{ define "datapadd" }}
datapadd( {{- printf "%d" . -}} )
{{ end }}
{{ define "dataadd" }}
dataadd( {{- . -}} )
{{ end }}
package main

import "os"
import "bytes"

var datap int
var data []byte

func writeb(repeat int) {
	os.Stdout.Write(bytes.Repeat(data[datap : datap+1], repeat))
}

func readb() {
	os.Stdin.Read(data[datap : datap+1])
}

func datapadd(delta int) {
	datap += delta
	if datap < 0 {
		panic("Data pointer is out of bounds")
	}
	if datap >= len(data) {
		newdata := make([]byte, datap*2)
		copy(newdata, data)
		data = newdata
	}
}

func dataadd(delta byte) {
	data[datap]+=delta
}

func main() {
	data = make([]byte, {{ .InitialDataSize }})

	{{ range .Body }}
	{{ . }}
	{{ end }}
}
`
